image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
environment:
  matrix:
    - PLATFORM: x64
      arch: " Win64"
    - PLATFORM: Win32
      arch: ""
init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - echo %generator%
before_build:
  - mkdir build
  - cd build
  - cmake -G %generator% -DENABLE_INTERNAL_QUEUE_H:BOOL=ON ..
build:
  project: c:\projects\libebur128\build\libebur128.sln