image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
platform:
  - x64
environment:
  matrix:
    - arch: " Win64"
    - arch: ""
init:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - echo %generator%
before_build:
  - mkdir build
  - cd build
  - cmake -G %generator% ..
build:
  project: c:\projects\libebur128\build\libebur128.sln